[package]
name = "loong_ctrl"
version = "0.1.0"
authors = ["alain <zhengze01@gmail.com>"]
edition = "2021"


[lib]
crate_type = [ "staticlib", "cdylib", "rlib" ]


[dependencies]
thiserror = "1.0.20"
rand = "0.7.3"